spring:
  application:
    name: Overseer
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${DB_URL}${DB_NAME_LOCATION}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
