spring:
  application:
    name: Overseer
    assetDirectory: /Users/abengier/projects/bnfd/personal/overseer/assets/
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${DB_URL}${DB_NAME_LOCATION}${DB_PARAMS}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  log:
    file:
      location: "logs/OverseerApi"
  request:
    timeout: 2000
    connection:
      timeout: 200
      pool:
        route:
          max: 512
        max: 64
    pool:
      timeout: 200
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    enabled: true