spring:
  application:
    name: Overseer
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${DB_URL}${DB_NAME_LOCATION}${DB_PARAMS}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: ./target/classes/static/
springdoc:
  swagger-ui:
    enabled: true